In [ ]:
# %pip install seaborn

In [1]:
# Tips 데이타셋
## seaborn 내장 데이터셋
import seaborn as sns
import pandas as pd

In [2]:
#1 사용 가능한 데이타 섹 확인 방법
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [6]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [7]:
# 성별
df['sex'].unique()

['Female', 'Male']
Categories (2, str): ['Male', 'Female']

In [8]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [9]:
# 모든 범주형 변수의 고유값 개수
categorical_columns = df.select_dtypes(include=['category']).columns

for col in categorical_columns:
    print(f"{col}. {df[col].nunique()}개의 고유값")
    print(f"  값. {list(df[col].unique())}")
    print()

sex. 2개의 고유값
  값. ['Female', 'Male']

smoker. 2개의 고유값
  값. ['No', 'Yes']

day. 4개의 고유값
  값. ['Sun', 'Sat', 'Thur', 'Fri']

time. 2개의 고유값
  값. ['Dinner', 'Lunch']